import type { SolverFn } from './types';
import {
  mean_calc,
  var_p,
  var_u,
  sd_calc,
  cv_calc,
  zscore_calc,
  quartiles,
  outlier_iqr,
  freq_mean,
} from './descriptive';
import {
  comb_calc,
  cond_prob,
  bayes_ppv,
  prob_union,
  expectation_discrete,
  linear_ev,
  sum_indep,
  odds_ratio,
  risk_ratio,
} from './probability';
import {
  binom_prob,
  binom_ev,
  poisson_prob,
  geom_prob,
  hypergeom_prob,
  normal_prob,
  normal_range,
  binom_normal,
  exp_prob,
  unif_prob,
} from './distributions';
import {
  sample_mean_prob,
  clt_prob,
  sample_prop_prob,
  df_concept,
} from './sampling';
import {
  ci_mean_z,
  ci_mean_t,
  ci_prop,
  ci_var,
  sample_size,
} from './estimation';
import {
  test_mean_z,
  test_mean_t,
  test_prop,
  test_var,
  test_f,
  test_pooled_t,
  test_welch,
  test_paired,
  test_two_prop,
  power_calc,
  test_conclusion,
} from './testing';
import { chi2_expected, chi2_indep, chi2_gof } from './chi2';
import {
  reg_slope,
  reg_predict,
  corr_calc,
  r2_calc,
  reg_t_test,
  corr_test,
  anova_oneway,
  anova_table,
  ma_calc,
} from './regression';
import { concept } from './concept';

export const SOLVERS: Record<string, SolverFn> = {
  mean_calc,
  var_p,
  var_u,
  sd_calc,
  cv_calc,
  zscore_calc,
  quartiles,
  outlier_iqr,
  freq_mean,
  comb_calc,
  cond_prob,
  bayes_ppv,
  prob_union,
  expectation_discrete,
  linear_ev,
  sum_indep,
  odds_ratio,
  risk_ratio,
  binom_prob,
  binom_ev,
  poisson_prob,
  geom_prob,
  hypergeom_prob,
  normal_prob,
  normal_range,
  binom_normal,
  exp_prob,
  unif_prob,
  sample_mean_prob,
  clt_prob,
  sample_prop_prob,
  df_concept,
  ci_mean_z,
  ci_mean_t,
  ci_prop,
  ci_var,
  sample_size,
  test_mean_z,
  test_mean_t,
  test_prop,
  test_var,
  test_f,
  test_pooled_t,
  test_welch,
  test_paired,
  test_two_prop,
  power_calc,
  test_conclusion,
  chi2_expected,
  chi2_indep,
  chi2_gof,
  reg_slope,
  reg_predict,
  corr_calc,
  r2_calc,
  reg_t_test,
  corr_test,
  anova_oneway,
  anova_table,
  ma_calc,
  concept,
};

export type { SolvedQuestion, Choice, ConceptItem } from './types';
